//-------------------------- File Dispaly.h -----------------------------------

#ifndef SML_DISPLAY_H_
#define SML_DISPLAY_H_

//-----------------------------------------------------------------------------
// Headers
//-----------------------------------------------------------------------------

#include <vector>
#include <string>

#include <SMLib/Video/VideoExport.h>
#include <SMLib/Video/VideoMode.h>
namespace sml
{
    namespace video
    {
        class SML_VIDEO_API Display
        {   
            public:
                //-------------------------------------------------------------
                // Doing request to the operating system
                //-------------------------------------------------------------
                VideoMode GetCurrentDesktopMode() const;

                //-------------------------------------------------------------
                // Setting up a custom mode for this display
                //-------------------------------------------------------------
                //bool SetDesktopMode(const VideoMode& mode);
            
            protected:
                //-------------------------------------------------------------
                // Base class for work with video displays
                //-------------------------------------------------------------
                friend class DisplayManager;

                //-------------------------------------------------------------
                // A default constructor
                // 
                // Instances can be generated by a displays manager only.
                //-------------------------------------------------------------
                Display();

                Display(uint32_t index, 
                        const char* adapterName, 
                        const char* adapterDesc,
                        const char* monitorDesc,
                        bool isPrimary);

                //-------------------------------------------------------------
                // A destructor
                // 
                // Instances can be destroyed by a displays manager only.
                //-------------------------------------------------------------
                ~Display();

                //-------------------------------------------------------------
                // All supported modes for this diaplay
                //-------------------------------------------------------------
                std::vector<VideoMode> _displayModes;


                
            private:
                //-------------------------------------------------------------
                // Member fields
                //-------------------------------------------------------------
                uint32_t    m_Index;        
                std::string m_AdapterName;  
                std::string m_AdapterDesc;
                std::string m_MonitorDesc;
                bool        m_isPrimary;

        };
    } // namspace video
} // namspace sml
#endif // !SML_DISPLAY_H_
//---------------------- End of file Display.h --------------------------------
